#*🤖Este Pipeline de CI se activa al PUSHEAR o MERGEAR en ramas de tareas que no sean QA ni Main, y consiste en ejecutar los tests de una US e importar los resultados a Jira!🚀
#*👩🏻‍🔬Para utilizar este Pipeline de Ari, sigue los siguientes pasos:
#todo: 1 -> Crea tu propio archivo sanity.yml con tu username de GitHub, ejemplo sanity-saiotest.yml
#todo: 2 -> Copia el contenido de este archivo yml y pégalo en tu nuevo archivo yml con tu username.
#todo: 3 -> Modifica el trigger del Push en donde dice "TuBranchAqui", coloca tu nombre tal cual de tu rama git.
#todo: 4 -> Modifica el archivo de prueba a ejectuar en el script del "yarn test" (ver ejemplo en este archivo)
#todo: 5 -> Modifica la propiedad: "testExecKey" con tu ID del TX de Jira para importar automáticamente el resultado.
#todo: 6 -> Recuerda modificar el projectKey correspondiente, si estás en L3, debe ser GX3 y así...
#todo: 7 -> Listo! Guarda los cambios (git add + git commit) y pushea (git push) para ejectutar este Pipeline!
#*Resultado: Debería ejecutarse este Pipeline de GitHub Actions y correr cada uno de los Jobs declarados aquí.

name: 🤖CI run SanityTest Execution🧪
run-name: ${{github.actor}}👨🏻‍🔬 ran SanityTest in ${{github.ref_name}}

on:
  push:
    branches: ['test/GX3-1861/ToolsQA/Elements/TextBoxFillFormAndSubmit'] #! Cambia "TuBranchAqui" por el nombre de tu rama de tarea.

jobs:
  SanityTest:
    runs-on: ubuntu-latest

    steps:
    - name: 💻Checkout
      uses: actions/checkout@v3

    - name: 💿Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: 💿Yarn Setup
      uses: DerYeger/yarn-setup-action@master
      with:
        node-version: 20

    - name: 🧬Install All Dependencies
      run: |
        yarn

    - name: 🧪Cypress Run Test Coverage
      uses: cypress-io/github-action@v4
      with:
        browser: chrome
        command: | #todo: EDITAR AQUÍ EL ARCHIVO SUITE A EJECUTAR:
          yarn test:chrome cypress/e2e/Tests/Elements/GX3-1861_form.cy.js

    - name: 📬Generate JUnit/Mocha Report
      if: always()
      run: |
        yarn chrome:report

    - name: ✅Import Test Results to Xray
      if: always()
      uses: mikepenz/xray-action@v2
      with: #OPCIONES PARA IMPORTAR LOS RESULTADOS DE PRUEBA A JIRA XRAY:
        username: ${{secrets.XRAY_CLIENT_ID}}
        password: ${{secrets.XRAY_CLIENT_SECRET}}
        testFormat: 'junit' #! NO CAMBIAR
        testPaths: 'cypress/tests_results/junit/chrome_regression_report.xml' #! NO CAMBIAR
        testExecKey: 'GX3-1861' #todo: EDITAR AQUÍ EL TEST EXECUTION A IMPORTAR LAS PRUEBAS.
        projectKey: 'GX3' #todo: EDITAR EN CASO DE TRABAJAR CON OTRO PROYECTO.

    - name: 🔔Slack Notification of Done
      if: always()
      uses: rtCamp/action-slack-notify@v2.2.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: Ari✨
        SLACK_MESSAGE: ':test_tube: BLACKHOLE Cypress Project -- Sanity Test Execution is Done and imported to Jira :rocket:'
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://image.cdn2.seaart.ai/2023-12-06/clo9g0h4msbc73ac2sog/99e1abc36f32945cd4bacf5ee7448e96194545f7_high.webp
